# Besu Node 2 Configuration
network-id=1337
sync-mode="FAST"

# RPC Configuration
rpc-http-enabled=true
rpc-http-host="127.0.0.1"
rpc-http-port=8555
rpc-http-cors-origins=["*"]
rpc-http-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]

# WS Configuration
rpc-ws-enabled=true
rpc-ws-host="127.0.0.1"
rpc-ws-port=8556
rpc-ws-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]

# P2P Configuration
p2p-enabled=true
p2p-host="127.0.0.1"
p2p-port=30304
p2p-peer-upper-bound=25

# Data Directory
data-path="./data/node2"

# Genesis Configuration
genesis-file="./genesis.json"

# Mining Configuration
miner-enabled=false
miner-coinbase="0x0000000000000000000000000000000000000000"

# Logging
logging="INFO"

# Metrics
metrics-enabled=true
metrics-host="127.0.0.1"
metrics-port=9555

# Privacy
privacy-enabled=false

# Network Discovery
discovery-enabled=true

# Gas Configuration
target-gas-limit=8000000
