# Besu Node 1 Configuration (Latest Version Compatible)
network-id=1337
sync-mode="FAST"

# RPC Configuration
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]

# WS Configuration
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546
rpc-ws-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]

# P2P Configuration
p2p-host="0.0.0.0"
p2p-port=30303

# Data Directory
data-path="./data/node1"

# Genesis Configuration
genesis-file="./genesis.json"

# Mining Configuration
miner-enabled=false

# Logging
logging="INFO"

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# Gas Configuration
target-gas-limit=8000000
