version: '3.8'

services:
  besu-node1:
    image: hyperledger/besu:latest
    container_name: besu-node1
    ports:
      - "8545:8545"  # RPC HTTP
      - "8546:8546"  # RPC WS
      - "30303:30303"  # P2P
      - "9545:9545"  # Metrics
    volumes:
      - ./besu-node1.toml:/etc/besu/besu.toml
      - ./genesis.json:/etc/besu/genesis.json
      - node1-data:/var/lib/besu
    command: >
      --config-file=/etc/besu/besu.toml
      --genesis-file=/etc/besu/genesis.json
      --data-path=/var/lib/besu
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=["*"]
      --rpc-http-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --rpc-ws-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]
      --p2p-enabled
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --metrics-enabled
      --metrics-host=0.0.0.0
      --metrics-port=9545
      --network-id=1337
      --sync-mode=FAST
      --miner-enabled=false
      --logging=INFO
    networks:
      - besu-network

  besu-node2:
    image: hyperledger/besu:latest
    container_name: besu-node2
    ports:
      - "8555:8545"  # RPC HTTP
      - "8556:8546"  # RPC WS
      - "30304:30303"  # P2P
      - "9555:9545"  # Metrics
    volumes:
      - ./besu-node2.toml:/etc/besu/besu.toml
      - ./genesis.json:/etc/besu/genesis.json
      - node2-data:/var/lib/besu
    command: >
      --config-file=/etc/besu/besu.toml
      --genesis-file=/etc/besu/genesis.json
      --data-path=/var/lib/besu
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=["*"]
      --rpc-http-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --rpc-ws-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]
      --p2p-enabled
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --metrics-enabled
      --metrics-host=0.0.0.0
      --metrics-port=9545
      --network-id=1337
      --sync-mode=FAST
      --miner-enabled=false
      --logging=INFO
    networks:
      - besu-network
    depends_on:
      - besu-node1

  besu-node3:
    image: hyperledger/besu:latest
    container_name: besu-node3
    ports:
      - "8565:8545"  # RPC HTTP
      - "8566:8546"  # RPC WS
      - "30305:30303"  # P2P
      - "9565:9545"  # Metrics
    volumes:
      - ./besu-node3.toml:/etc/besu/besu.toml
      - ./genesis.json:/etc/besu/genesis.json
      - node3-data:/var/lib/besu
    command: >
      --config-file=/etc/besu/besu.toml
      --genesis-file=/etc/besu/genesis.json
      --data-path=/var/lib/besu
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-http-cors-origins=["*"]
      --rpc-http-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]
      --rpc-ws-enabled
      --rpc-ws-host=0.0.0.0
      --rpc-ws-port=8546
      --rpc-ws-apis=["ETH","NET","WEB3","DEBUG","ADMIN","MINER","CLIQUE"]
      --p2p-enabled
      --p2p-host=0.0.0.0
      --p2p-port=30303
      --metrics-enabled
      --metrics-host=0.0.0.0
      --metrics-port=9545
      --network-id=1337
      --sync-mode=FAST
      --miner-enabled=false
      --logging=INFO
    networks:
      - besu-network
    depends_on:
      - besu-node1
      - besu-node2

volumes:
  node1-data:
  node2-data:
  node3-data:

networks:
  besu-network:
    driver: bridge
